server:
  env: "local"
  host: "localhost"
  port: "8080"
  timeout: 4s
  idle_timeout: 60s

database:
  host: "localhost"
  port:  "5432"
  user: "postgres"
  password: "postgres"
  name: "postgres"
  sslmode: "disable"
  maxconns: 20
  minconns: 5
  maxconnlifetime: 30m
  maxconnidletime: 5m
  healthcheckperiod: 1m